### ISSUE TITLE
Generate Final Terrain NavMesh

### ISSUE THREAD

**Issue by Polytonic** [ludimation/Winter#2]
Prior to submission, we'll need to generate the final NavMesh from the final Terrain, pending from @diokatsu.  

Does your pathfinding script depend on specific coordinates on the NavMesh?  Or can the general script be ported (and just change the coordinates afterwards?).

**Comment by Gimsor** [comment]
The pathfinding script will be dependent on world coordinates.  The general script can be ported, and we will have to set appropriate coordinates.  I have uploaded a very simple script (Winter/Assets/Scripts/run.cs) allowing the prefab it's attached to to move to a specific world-coordinate point, as well as a script (Winter/Assets/Scripts/testNavScript.cs) allowing an assigned NavMeshAgent to move to the prefab this script is attached to.

**Comment by Polytonic** [comment]
Okay, sounds good.  

I managed to move the Terrain prefab into a separate (forced-text) project to try and fix all these merge conflict problems once and for all.  So far so good.  I can't generate NavMeshes on the free license of Unity, so once I get it all setup, you'll have to generate that, or figure out how to import the existing stuff across projects.

**Comment by ludimation** [comment]
Awesome. Thanks for taking that on Kevin! Hopefully this will be the _nocks
on wood_ LAST of our unity/external source control woes :)

See you guys tomorrow!

**Comment by Polytonic** [comment]
For closure and documentation: we're back to using the original Unity project, since it was too difficult to port everything across.  A (mostly) empty Unity project template is in the build branch, for future projects.  

As for the nav mesh, I think we're mostly set, so I'm going to close this issue.
