### ISSUE TITLE
OS-Dependent Line Endings (CRLF vs. LF)

### ISSUE THREAD

**Issue by Polytonic** [ludimation/Winter#3]
As we were discussing earlier, we should all be using the same line-endings.  For the unfamiliar:  UNIX systems (Linux, Mac OS X) use only a Line-Feed character `\n` to terminate a line.  Windows uses both a Carriage Return `\r` and a Line-Feed character (for a combined `\r\n` to terminate a line).  To get us all on the same page, we should all be using LF only.  Here's how to fix it:

**If Using Microsoft Windows**

@diokatsu 
@Gimsor 
@jump4r 

In your Git command line interface, enter the following:
`git config --global core.autocrlf true`

This will convert your local files to the correct CRLF line endings when checking out files, while keeping copies on the remote as LF.  

*\* Otherwise ...**
@ludimation in Terminal, enter:
`git config --global core.autocrlf input`

For more information and general reference, see [this link](http://git-scm.com/book/ch7-1.html#Formatting-and-Whitespace).  

I may or may not add a repository attributes file to enforce this setting, but for now, this is the simpler approach.  

Drop me a note or write a comment here when you've done this, and we can close the issue when everyone has the same configuration.

**Comment by ludimation** [comment]
On Mon, Nov 4, 2013 at 12:53 AM, Kevin Fung notifications@github.comwrote:

> git config --global core.autocrlf input

Done!

[ d ]
